name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Release
        uses: "softprops/action-gh-release@v2"
        with:
          body: >
            See release in the main repository
            [`${{ github.ref_name }}`](https://github.com/yann-eugone/test-monorepo/releases/tag/${{ github.ref_name }})
          generate_release_notes: true
